// certificate-generator/src/main/webapp/app/entities/plainte/plainte-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IPlainte } from 'app/shared/model/plainte.model';

@Component({
  selector: 'jhi-plainte-detail',
  templateUrl: './plainte-detail.component.html',
})
export class PlainteDetailComponent implements OnInit {
  plainte: IPlainte | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ plainte }) => (this.plainte = plainte));
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="plainte">
            <h2><span>Plainte</span> {{ plainte.id }}</h2>

            <hr>

            <jhi-alert-error></jhi-alert-error>

            <dl class="row-md jh-entity-details">
                <dt><span>Telephone</span></dt>
                <dd>
                    <span>{{ plainte.telephone }}</span>
                </dd>
                <dt><span>Local Id</span></dt>
                <dd>
                    <span>{{ plainte.localId }}</span>
                </dd>
                <dt><span>Code</span></dt>
                <dd>
                    <span>{{ plainte.code }}</span>
                </dd>
                <dt><span>Commentaire</span></dt>
                <dd>
                    <span>{{ plainte.commentaire }}</span>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span>Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/plainte', plainte.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span>Edit</span>
            </button>
        </div>
    </div>
</div>

// certificate-generator/src/main/webapp/app/entities/plainte/plainte-detail.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './plainte.reducer';
import { IPlainte } from 'app/shared/model/plainte.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IPlainteDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const PlainteDetail = (props: IPlainteDetailProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const { plainteEntity } = props;
  return (
    <Row>
      <Col md="8">
        <h2>
          Plainte [<b>{plainteEntity.id}</b>]
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="telephone">Telephone</span>
          </dt>
          <dd>{plainteEntity.telephone}</dd>
          <dt>
            <span id="localId">Local Id</span>
          </dt>
          <dd>{plainteEntity.localId}</dd>
          <dt>
            <span id="code">Code</span>
          </dt>
          <dd>{plainteEntity.code}</dd>
          <dt>
            <span id="commentaire">Commentaire</span>
          </dt>
          <dd>{plainteEntity.commentaire}</dd>
        </dl>
        <Button tag={Link} to="/plainte" replace color="info">
          <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/plainte/${plainteEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
        </Button>
      </Col>
    </Row>
  );
};

const mapStateToProps = ({ plainte }: IRootState) => ({
  plainteEntity: plainte.entity,
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(PlainteDetail);
