// certificate-generator/src/main/webapp/app/entities/tracker-entity-instance/tracker-entity-instance.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpHeaders, HttpResponse } from '@angular/common/http';
import { ActivatedRoute, ParamMap, Router, Data } from '@angular/router';
import { Subscription, combineLatest } from 'rxjs';
import { JhiEventManager } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { ITrackerEntityInstance } from 'app/shared/model/tracker-entity-instance.model';

import { ITEMS_PER_PAGE } from 'app/shared/constants/pagination.constants';
import { TrackerEntityInstanceService } from './tracker-entity-instance.service';
import { TrackerEntityInstanceDeleteDialogComponent } from './tracker-entity-instance-delete-dialog.component';

@Component({
  selector: 'jhi-tracker-entity-instance',
  templateUrl: './tracker-entity-instance.component.html',
})
export class TrackerEntityInstanceComponent implements OnInit, OnDestroy {
  trackerEntityInstances?: ITrackerEntityInstance[];
  eventSubscriber?: Subscription;
  totalItems = 0;
  itemsPerPage = ITEMS_PER_PAGE;
  page!: number;
  predicate!: string;
  ascending!: boolean;
  ngbPaginationPage = 1;

  constructor(
    protected trackerEntityInstanceService: TrackerEntityInstanceService,
    protected activatedRoute: ActivatedRoute,
    protected router: Router,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal
  ) {}

  loadPage(page?: number, dontNavigate?: boolean): void {
    const pageToLoad: number = page || this.page || 1;

    this.trackerEntityInstanceService
      .query({
        page: pageToLoad - 1,
        size: this.itemsPerPage,
        sort: this.sort(),
      })
      .subscribe(
        (res: HttpResponse<ITrackerEntityInstance[]>) => this.onSuccess(res.body, res.headers, pageToLoad, !dontNavigate),
        () => this.onError()
      );
  }

  ngOnInit(): void {
    this.handleNavigation();
    this.registerChangeInTrackerEntityInstances();
  }

  protected handleNavigation(): void {
    combineLatest(this.activatedRoute.data, this.activatedRoute.queryParamMap, (data: Data, params: ParamMap) => {
      const page = params.get('page');
      const pageNumber = page !== null ? +page : 1;
      const sort = (params.get('sort') ?? data['defaultSort']).split(',');
      const predicate = sort[0];
      const ascending = sort[1] === 'asc';
      if (pageNumber !== this.page || predicate !== this.predicate || ascending !== this.ascending) {
        this.predicate = predicate;
        this.ascending = ascending;
        this.loadPage(pageNumber, true);
      }
    }).subscribe();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: ITrackerEntityInstance): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInTrackerEntityInstances(): void {
    this.eventSubscriber = this.eventManager.subscribe('trackerEntityInstanceListModification', () => this.loadPage());
  }

  delete(trackerEntityInstance: ITrackerEntityInstance): void {
    const modalRef = this.modalService.open(TrackerEntityInstanceDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.trackerEntityInstance = trackerEntityInstance;
  }

  sort(): string[] {
    const result = [this.predicate + ',' + (this.ascending ? 'asc' : 'desc')];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected onSuccess(data: ITrackerEntityInstance[] | null, headers: HttpHeaders, page: number, navigate: boolean): void {
    this.totalItems = Number(headers.get('X-Total-Count'));
    this.page = page;
    if (navigate) {
      this.router.navigate(['/tracker-entity-instance'], {
        queryParams: {
          page: this.page,
          size: this.itemsPerPage,
          sort: this.predicate + ',' + (this.ascending ? 'asc' : 'desc'),
        },
      });
    }
    this.trackerEntityInstances = data || [];
    this.ngbPaginationPage = this.page;
  }

  protected onError(): void {
    this.ngbPaginationPage = this.page ?? 1;
  }
}

<div>
    <h2 id="page-heading">
        <span>Tracker Entity Instances</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-tracker-entity-instance" [routerLink]="['/tracker-entity-instance/new']">
            <fa-icon icon="plus"></fa-icon>
            <span>
            Create a new Tracker Entity Instance
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="trackerEntityInstances?.length === 0">
        <span>No trackerEntityInstances found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="trackerEntityInstances && trackerEntityInstances.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" [callback]="loadPage.bind(this)">
                    <th scope="col"  jhiSortBy="id"><span>ID</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="uid"><span>Uid</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="nom"><span>Nom</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="prenom"><span>Prenom</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="sexe"><span>Sexe</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="profession"><span>Profession</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="age"><span>Age</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="region"><span>Region</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="prefecture"><span>Prefecture</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="sousPrefecture"><span>Sous Prefecture</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="quartier"><span>Quartier</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="village"><span>Village</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="telephone"><span>Telephone</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="localId"><span>Local Id</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="code"><span>Code</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="certificate"><span>Certificate</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let trackerEntityInstance of trackerEntityInstances ;trackBy: trackId">
                    <td><a [routerLink]="['/tracker-entity-instance', trackerEntityInstance.id, 'view']">{{ trackerEntityInstance.id }}</a></td>
                    <td>{{ trackerEntityInstance.uid }}</td>
                    <td>{{ trackerEntityInstance.nom }}</td>
                    <td>{{ trackerEntityInstance.prenom }}</td>
                    <td>{{ trackerEntityInstance.sexe }}</td>
                    <td>{{ trackerEntityInstance.profession }}</td>
                    <td>{{ trackerEntityInstance.age }}</td>
                    <td>{{ trackerEntityInstance.region }}</td>
                    <td>{{ trackerEntityInstance.prefecture }}</td>
                    <td>{{ trackerEntityInstance.sousPrefecture }}</td>
                    <td>{{ trackerEntityInstance.quartier }}</td>
                    <td>{{ trackerEntityInstance.village }}</td>
                    <td>{{ trackerEntityInstance.telephone }}</td>
                    <td>{{ trackerEntityInstance.localId }}</td>
                    <td>{{ trackerEntityInstance.code }}</td>
                    <td>{{ trackerEntityInstance.certificate }}</td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/tracker-entity-instance', trackerEntityInstance.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/tracker-entity-instance', trackerEntityInstance.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(trackerEntityInstance)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <div *ngIf="trackerEntityInstances && trackerEntityInstances.length > 0">
        <div class="row justify-content-center">
            <jhi-item-count [page]="page" [total]="totalItems" [itemsPerPage]="itemsPerPage"></jhi-item-count>
        </div>

        <div class="row justify-content-center">
            <ngb-pagination [collectionSize]="totalItems" [(page)]="ngbPaginationPage" [pageSize]="itemsPerPage" [maxSize]="5" [rotate]="true" [boundaryLinks]="true" (pageChange)="loadPage($event)"></ngb-pagination>
        </div>
    </div>
</div>

// certificate-generator/src/main/webapp/app/entities/tracker-entity-instance/tracker-entity-instance.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { ICrudGetAllAction, getSortState, IPaginationBaseState, JhiPagination, JhiItemCount } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './tracker-entity-instance.reducer';
import { ITrackerEntityInstance } from 'app/shared/model/tracker-entity-instance.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';
import { overridePaginationStateWithQueryParams } from 'app/shared/util/entity-utils';

export interface ITrackerEntityInstanceProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const TrackerEntityInstance = (props: ITrackerEntityInstanceProps) => {
  const [paginationState, setPaginationState] = useState(
    overridePaginationStateWithQueryParams(getSortState(props.location, ITEMS_PER_PAGE), props.location.search)
  );

  const getAllEntities = () => {
    props.getEntities(paginationState.activePage - 1, paginationState.itemsPerPage, `${paginationState.sort},${paginationState.order}`);
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`;
    if (props.location.search !== endURL) {
      props.history.push(`${props.location.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  useEffect(() => {
    const params = new URLSearchParams(props.location.search);
    const page = params.get('page');
    const sort = params.get('sort');
    if (page && sort) {
      const sortSplit = sort.split(',');
      setPaginationState({
        ...paginationState,
        activePage: +page,
        sort: sortSplit[0],
        order: sortSplit[1],
      });
    }
  }, [props.location.search]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === 'asc' ? 'desc' : 'asc',
      sort: p,
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage,
    });

  const { trackerEntityInstanceList, match, loading, totalItems } = props;
  return (
    <div>
      <h2 id="tracker-entity-instance-heading">
        Tracker Entity Instances
        <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
          <FontAwesomeIcon icon="plus" />
          &nbsp; Create new Tracker Entity Instance
        </Link>
      </h2>
      <div className="responsive-table">
        {trackerEntityInstanceList && trackerEntityInstanceList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  ID <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('uid')}>
                  Uid <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('nom')}>
                  Nom <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('prenom')}>
                  Prenom <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('sexe')}>
                  Sexe <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('profession')}>
                  Profession <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('age')}>
                  Age <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('region')}>
                  Region <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('prefecture')}>
                  Prefecture <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('sousPrefecture')}>
                  Sous Prefecture <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('quartier')}>
                  Quartier <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('village')}>
                  Village <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('telephone')}>
                  Telephone <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('localId')}>
                  Local Id <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('code')}>
                  Code <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('certificate')}>
                  Certificate <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {trackerEntityInstanceList.map((trackerEntityInstance, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${trackerEntityInstance.id}`} color="link" size="sm">
                      {trackerEntityInstance.id}
                    </Button>
                  </td>
                  <td>{trackerEntityInstance.uid}</td>
                  <td>{trackerEntityInstance.nom}</td>
                  <td>{trackerEntityInstance.prenom}</td>
                  <td>{trackerEntityInstance.sexe}</td>
                  <td>{trackerEntityInstance.profession}</td>
                  <td>{trackerEntityInstance.age}</td>
                  <td>{trackerEntityInstance.region}</td>
                  <td>{trackerEntityInstance.prefecture}</td>
                  <td>{trackerEntityInstance.sousPrefecture}</td>
                  <td>{trackerEntityInstance.quartier}</td>
                  <td>{trackerEntityInstance.village}</td>
                  <td>{trackerEntityInstance.telephone}</td>
                  <td>{trackerEntityInstance.localId}</td>
                  <td>{trackerEntityInstance.code}</td>
                  <td>{trackerEntityInstance.certificate}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${trackerEntityInstance.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" /> <span className="d-none d-md-inline">View</span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${trackerEntityInstance.id}/edit?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="primary"
                        size="sm"
                      >
                        <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${trackerEntityInstance.id}/delete?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="danger"
                        size="sm"
                      >
                        <FontAwesomeIcon icon="trash" /> <span className="d-none d-md-inline">Delete</span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && <div className="alert alert-warning">No Tracker Entity Instances found</div>
        )}
      </div>
      {props.totalItems ? (
        <div className={trackerEntityInstanceList && trackerEntityInstanceList.length > 0 ? '' : 'd-none'}>
          <Row className="justify-content-center">
            <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} />
          </Row>
          <Row className="justify-content-center">
            <JhiPagination
              activePage={paginationState.activePage}
              onSelect={handlePagination}
              maxButtons={5}
              itemsPerPage={paginationState.itemsPerPage}
              totalItems={props.totalItems}
            />
          </Row>
        </div>
      ) : (
        ''
      )}
    </div>
  );
};

const mapStateToProps = ({ trackerEntityInstance }: IRootState) => ({
  trackerEntityInstanceList: trackerEntityInstance.entities,
  loading: trackerEntityInstance.loading,
  totalItems: trackerEntityInstance.totalItems,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(TrackerEntityInstance);
