// certificate-generator/src/main/webapp/app/entities/signature/signature-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { JhiDataUtils } from 'ng-jhipster';

import { ISignature } from 'app/shared/model/signature.model';

@Component({
  selector: 'jhi-signature-detail',
  templateUrl: './signature-detail.component.html',
})
export class SignatureDetailComponent implements OnInit {
  signature: ISignature | null = null;

  constructor(protected dataUtils: JhiDataUtils, protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ signature }) => (this.signature = signature));
  }

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(contentType = '', base64String: string): void {
    this.dataUtils.openFile(contentType, base64String);
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="signature">
            <h2><span>Signature</span> {{ signature.id }}</h2>

            <hr>

            <jhi-alert-error></jhi-alert-error>

            <dl class="row-md jh-entity-details">
                <dt><span>Authorite</span></dt>
                <dd>
                    <span>{{ signature.authorite }}</span>
                </dd>
                <dt><span>Signature</span></dt>
                <dd>
                    <div *ngIf="signature.signature">
                        <a (click)="openFile(signature.signatureContentType, signature.signature)">
                            <img [src]="'data:' + signature.signatureContentType + ';base64,' + signature.signature" style="max-width: 100%;" alt="signature image"/>
                        </a>
                        {{ signature.signatureContentType }}, {{ byteSize(signature.signature) }}
                    </div>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span>Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/signature', signature.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span>Edit</span>
            </button>
        </div>
    </div>
</div>

// certificate-generator/src/main/webapp/app/entities/signature/signature-detail.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { ICrudGetAction, openFile, byteSize } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './signature.reducer';
import { ISignature } from 'app/shared/model/signature.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface ISignatureDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const SignatureDetail = (props: ISignatureDetailProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const { signatureEntity } = props;
  return (
    <Row>
      <Col md="8">
        <h2>
          Signature [<b>{signatureEntity.id}</b>]
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="authorite">Authorite</span>
          </dt>
          <dd>{signatureEntity.authorite}</dd>
          <dt>
            <span id="signature">Signature</span>
          </dt>
          <dd>
            {signatureEntity.signature ? (
              <div>
                {signatureEntity.signatureContentType ? (
                  <a onClick={openFile(signatureEntity.signatureContentType, signatureEntity.signature)}>
                    <img
                      src={`data:${signatureEntity.signatureContentType};base64,${signatureEntity.signature}`}
                      style={{ maxHeight: '30px' }}
                    />
                  </a>
                ) : null}
                <span>
                  {signatureEntity.signatureContentType}, {byteSize(signatureEntity.signature)}
                </span>
              </div>
            ) : null}
          </dd>
        </dl>
        <Button tag={Link} to="/signature" replace color="info">
          <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/signature/${signatureEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
        </Button>
      </Col>
    </Row>
  );
};

const mapStateToProps = ({ signature }: IRootState) => ({
  signatureEntity: signature.entity,
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(SignatureDetail);
